
# setup proxy
export NO_PROXY=''
proxy_user=''
proxy_pass=''
proxy_host=''
proxy_port=''
function setproxy() {
    export {http,https,ftp}_proxy="http://$proxy_user:$proxy_pass@$proxy_host:$proxy_port"
}

# colorize cat
cat() {
    local out colored
    out=$(/bin/cat $@)
    colored=$(echo $out | pygmentize -f console -g 2>/dev/null)
    [[ -n $colored ]] && echo "$colored" || echo "$out"
}

# man
man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

# Unset Proxy
function unsetproxy() {
    unset {http,https,ftp}_proxy
}

# Java Setup
if [ -d "/usr/libexec/java_home" ]
then
    export JAVA_HOME=$(/usr/libexec/java_home)
fi

# VirtualEnv Setup
export WORKON_HOME=~/.virtualenvs
if [ -f "/usr/bin/virtualenvwrapper.sh" ]
then 
    source /usr/bin/virtualenvwrapper.sh;
fi

if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]
then
    source /usr/local/bin/virtualenvwrapper.sh;
fi

# Aliases

# mac
alias pc="pwd | pbcopy"
alias notify='$@ && echo ""; echo "Process Completed." | terminal-notifier -sound default'

## python
alias pyc="find . -name '*.pyc' -delete"
alias n="nosetests"
alias nx="nosetests -x"
alias nxp="nosetests -x --pdb"
alias pypi_register='python setup.py sdist upload -r $1'
alias pypi_upload='python setup.py sdist upload -r $1'

# docker-machine
eval "$(docker-machine env default)"

# source work bashrc
source ~/.work.bashrc

# z
source `brew --prefix`/etc/profile.d/z.sh
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# vagrant
alias vsh="vagrant ssh"
alias vup="vagrant up"
alias vupp="vagrant up --provision"
alias vstat="vagrant status"
alias vprov="vagrant provision"
alias vhalt="vagrant halt"
alias vdest="vagrant destroy"
alias vdestf="vagrant destroy --force"
alias vsnap="vagrant snap"

# network tools
alias list_listening='netstat -an -ptcp | grep LISTEN'

# for macports
export PATH=/opt/local/bin:$PATH

# for python2.7
export PATH=/usr/local/Cellar/python/2.7.10_2/bin:$PATH
export CLICOLOR
export CLICOLOR
