---
- hosts: localhost
  vars:
  - user_home: "/home/{{ user }}"
  - dotfiles_home: "~/.dotfiles"
  tasks:
  - debug: msg="user is {{ user }}; user_home {{ user_home }}; OS {{ ansible_os_family }}"


  # setup bashrc
  - file: src=~/.dotfiles/data/{{ item.path }} dest=~/{{ item.dst }} force=yes state=link
    with_items:
      - { path: 'bash/bashrc', dst: '.bashrc' }
      - { path: 'bash/bashrc', dst: '.bash_profile' }
      - { path: 'git/gitconfig', dst: '.gitconfig'}
      - { path: 'iterm2/inputrc', dst: '.inputrc' }
      - { path: 'pypi/pypirc', dst: '.pypirc' }
      - { path: 'vim/vimrc', dst: '.vimrc' }
      - { path: 'zsh/zshrc', dst: '.zshrc' }
      - { path: 'tmux/tmux.conf', dst: '.tmux.conf' }

- hosts: localhost
  remote_user: root
  tasks:
  - name: Install Common Packages from pip
    pip: name={{ item.name }} state={{ item.state }}
    with_items: 
      - { name: pip, state: latest }
      - { name: virtualenv, state: latest }
      - { name: virtualenvwrapper, state: latest }
      - { name: jedi, state: latest }
