---
- hosts: localhost
  remote_user: root
  tasks:

  - name: Downloading and enable the EPEL repository definitions.
    action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

  - yum: name=docker state=latest