
# setup proxy
export NO_PROXY=''
proxy_user=''
proxy_pass=''
proxy_host=''
proxy_port=''
function setproxy() {
    export {http,https,ftp}_proxy="http://$proxy_user:$proxy_pass@$proxy_host:$proxy_port"
}

# Unset Proxy
function unsetproxy() {
    unset {http,https,ftp}_proxy
}

# Java Setup
if [ -d "/usr/libexec/java_home" ]
then
    export JAVA_HOME=$(/usr/libexec/java_home)
fi

# VirtualEnv Setup
export WORKON_HOME=~/.virtualenvs
if [ -f "/usr/bin/virtualenvwrapper.sh" ]
then 
    source /usr/bin/virtualenvwrapper.sh;
fi

if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]
then
    source /usr/local/bin/virtualenvwrapper.sh;
fi

# Aliases
## python
alias pyc="find . -name '*.pyc' -delete"
alias n="nosetests"
alias nx="nosetests -x"
alias nxp="nosetests -x --pdb"
alias pypi_register='python setup.py sdist upload -r $1'
alias pypi_upload='python setup.py sdist upload -r $1'

# source work bashrc
source ~/.work.bashrc
