
# setup proxy
export NO_PROXY=''
proxy_user=''
proxy_pass=''
proxy_host=''
proxy_port=''
function setproxy() {
    export {http,https,ftp}_proxy="http://$proxy_user:$proxy_pass@$proxy_host:$proxy_port"
}

# Unset Proxy
function unsetproxy() {
    unset {http,https,ftp}_proxy
}

# Java Setup
export JAVA_HOME=$(/usr/libexec/java_home)

# VirtualEnv Setup
export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# Aliases
## python
alias pyc="find . -name '*.pyc' -delete"
alias n="nosetests"
alias nx="nosetests -x"
alias nxp="nosetests -x --pdb"

# source work bashrc
source ~/.work.bashrc
